# Generated by Django 4.2 on 2025-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsandevents",
            name="summary_kn",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_ml",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="summary_ta",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_kn",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_ml",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="newsandevents",
            name="title_ta",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
