# Generated by Django 4.2 on 2025-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_summary_es_course_summary_fr_course_title_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="summary_kn",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_ml",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="summary_ta",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_kn",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ml",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="title_ta",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_kn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_ml",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary_ta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_kn",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_ml",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="title_ta",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_kn",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="title_ta",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_kn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_ml",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="summary_ta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_kn",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_ml",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="title_ta",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
