# Generated by Django 4.2 on 2025-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_choice_choice_es_choice_choice_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="choice_kn",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_ml",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_ta",
            field=models.CharField(
                help_text="Enter the choice text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Content",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_kn",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_ml",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content_ta",
            field=models.CharField(
                help_text="Enter the question text that you want displayed",
                max_length=1000,
                null=True,
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_kn",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_ml",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_ta",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                null=True,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_kn",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_ml",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="description_ta",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the quiz",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_kn",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_ml",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title_ta",
            field=models.CharField(max_length=60, null=True, verbose_name="Title"),
        ),
    ]
