# Generated by Django 4.2.7 on 2025-05-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_choice_choice_kn_choice_choice_ml_choice_choice_ta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_es',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_fr',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_kn',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_ml',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_ru',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_ta',
        ),
    ]
